prod:

  profiles:

    prod: &prod
      vcenter: prod
      network: prod
      compute: medium

  roles:

    api:
      <<: *prod
      compute: large
      count: 12
      addresses:
        - 10.20.1.10
        - 10.20.1.11
        - 10.20.1.12
        - 10.20.1.13
        - 10.20.1.14
        - 10.20.1.15
        - 10.20.1.16
        - 10.20.1.17
        - 10.20.1.18
        - 10.20.1.19
        - 10.20.1.20
        - 10.20.1.21

    cui:
      <<: *prod
      count: 8
      addresses:
        - 10.20.2.10
        - 10.20.2.11
        - 10.20.2.13
        - 10.20.2.14
        - 10.20.2.15
        - 10.20.2.16
        - 10.20.2.17
        - 10.20.2.18